#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.8.3 on Mon Dec  3 11:51:41 2018
#

# This is an automatically generated file.
# Manual changes will be overwritten without warning!




import wx
from wxasync import WxAsyncApp

from cozmo_taste_game import GameEngine
from cozmo_taste_game.user_interface.UserInterface import UserInterface


class CozmoTasteGameInterface:
    """
    Boot straps a new instance of the CozmoTasteGame user interface
    """

    def __init__(self, game_engine : GameEngine, food_item_manager: FoodItemManager):
        self.game_engine = game_engine
        self.food_item_manager = food_item_manager


    async def MainLoop(self):
        app = WxAsyncApp()
        interface = UserInterface(self.game_engine, self. food_item_manager, None, wx.ID_ANY, "")
        app.SetTopWindow(interface)
        interface.Show()
        await app.MainLoop()
