# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.8.3 on Mon Dec  3 11:51:41 2018
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class EditFoodItemDialog(wx.Dialog):
				def __init__(self, *args, **kwds):
								# begin wxGlade: EditFoodItemDialog.__init__
								kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
								wx.Dialog.__init__(self, *args, **kwds)
								self.text_ctrl_1 = wx.TextCtrl(self, wx.ID_ANY, "")
								self.text_ctrl_2 = wx.TextCtrl(self, wx.ID_ANY, "")
								self.combo_box_1 = wx.ComboBox(self, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
								self.text_ctrl_3 = wx.TextCtrl(self, wx.ID_ANY, "")
								self.button_1 = wx.Button(self, wx.ID_ANY, "button_1")

								self.__set_properties()
								self.__do_layout()
								# end wxGlade

				def __set_properties(self):
								# begin wxGlade: EditFoodItemDialog.__set_properties
								self.SetTitle("Edit Food Item")
								_icon = wx.NullIcon
								_icon.CopyFromBitmap(wx.Bitmap("C:\\Source\\cs4500\\cozmo_taste_game\\cozmo.jpg", wx.BITMAP_TYPE_ANY))
								self.SetIcon(_icon)
								# end wxGlade

				def __do_layout(self):
								# begin wxGlade: EditFoodItemDialog.__do_layout
								grid_sizer_1 = wx.GridSizer(0, 2, 5, 5)
								label_2 = wx.StaticText(self, wx.ID_ANY, "Tag")
								grid_sizer_1.Add(label_2, 0, 0, 0)
								grid_sizer_1.Add(self.text_ctrl_1, 0, 0, 0)
								label_3 = wx.StaticText(self, wx.ID_ANY, "Name")
								grid_sizer_1.Add(label_3, 0, 0, 0)
								grid_sizer_1.Add(self.text_ctrl_2, 0, 0, 0)
								label_4 = wx.StaticText(self, wx.ID_ANY, "Group")
								grid_sizer_1.Add(label_4, 0, 0, 0)
								grid_sizer_1.Add(self.combo_box_1, 0, 0, 0)
								label_5 = wx.StaticText(self, wx.ID_ANY, "Taste")
								grid_sizer_1.Add(label_5, 0, 0, 0)
								grid_sizer_1.Add(self.text_ctrl_3, 0, 0, 0)
								grid_sizer_1.Add((20, 20), 0, 0, 0)
								grid_sizer_1.Add(self.button_1, 0, 0, 0)
								self.SetSizer(grid_sizer_1)
								grid_sizer_1.Fit(self)
								self.Layout()
								# end wxGlade

# end of class EditFoodItemDialog
